name: Publish package to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup Node.js environment
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'

      # Install yarn globally
      - name: Install Yarn
        run: npm i yarn@latest -g

      # Install dependencies using Yarn
      - name: Install Dependencies
        run: yarn

      # Build the packages
      - name: Build Packages
        run: yarn build

      # Create .npmrc file for GitHub Packages
      - name: Configure .npmrc
        run: |
          echo "@william2673:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_GITHUB_TOKEN }}" >> ~/.npmrc

      # Publish the package to GitHub Packages
      - name: Publish to GitHub Packages
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}
